CREATE TABLE IF NOT EXISTS PUBLIC.MPA (
    MPA_ID INT AUTO_INCREMENT PRIMARY KEY,
    NAME VARCHAR NOT NULL
);

CREATE TABLE IF NOT EXISTS PUBLIC.FILM (
    FILM_ID INT AUTO_INCREMENT PRIMARY KEY,
    NAME VARCHAR NOT NULL,
    DESCRIPTION VARCHAR NOT NULL,
    RELEASE_DATE TIMESTAMP,
    DURATION INT NOT NULL,
    MPA_ID INT,
    FOREIGN KEY (MPA_ID) REFERENCES PUBLIC.MPA(MPA_ID)
);

CREATE TABLE IF NOT EXISTS PUBLIC.GENRE (
    GENRE_ID INT AUTO_INCREMENT PRIMARY KEY,
    NAME VARCHAR NOT NULL
);

CREATE TABLE IF NOT EXISTS PUBLIC.FILM_GENRE (
    ID INT AUTO_INCREMENT PRIMARY KEY,
    FILM_ID INT NOT NULL,
    GENRE_ID INT NOT NULL,
    FOREIGN KEY (FILM_ID) REFERENCES PUBLIC.FILM(FILM_ID),
    FOREIGN KEY (GENRE_ID) REFERENCES PUBLIC.GENRE(GENRE_ID)
);

CREATE TABLE IF NOT EXISTS PUBLIC."USER" (
    USER_ID INT AUTO_INCREMENT PRIMARY KEY,
    EMAIL VARCHAR NOT NULL,
    LOGIN VARCHAR,
    NAME VARCHAR NOT NULL,
    BIRTHDAY TIMESTAMP
);

CREATE TABLE IF NOT EXISTS PUBLIC.LIKES_FROM_USERS (
    ID INT AUTO_INCREMENT PRIMARY KEY,
    FILM_ID INT NOT NULL,
    USER_ID INT NOT NULL,
    FOREIGN KEY (USER_ID) REFERENCES PUBLIC."USER"(USER_ID),
    FOREIGN KEY (FILM_ID) REFERENCES PUBLIC.FILM(FILM_ID)
);

CREATE TABLE IF NOT EXISTS PUBLIC.FRIENDS_IDS (
    ID INT AUTO_INCREMENT PRIMARY KEY,
    USER_ID INT NOT NULL,
    FRIEND_ID INT,
    FOREIGN KEY (USER_ID) REFERENCES PUBLIC."USER"(USER_ID),
    FOREIGN KEY (FRIEND_ID) REFERENCES PUBLIC."USER"(USER_ID)
);
